### ISSUE TITLE
Add Cuman to languages

### ISSUE THREAD

**Issue by martino-vic** [martino-vic/rtbwestoldturkic#13]

**Comment by martino-vic** [comment]
This throws following error: 

Traceback (most recent call last):
  File "/home/viktor/Documents/cldfvenv3.9/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/cldfbench/__main__.py", line 84, in main
    return args.main(args) or 0
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/commands/makecldf.py", line 24, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/cldfbench/cli_util.py", line 153, in with_dataset
    res = func(*arg, args)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/dataset.py", line 218, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/cldfbench/dataset.py", line 206, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "/home/viktor/Documents/GitHub/rtbwestoldturkic/lexibank_rtbwestoldturkic.py", line 154, in cmd_makecldf
    lex["ProsodicStructure"] = prosodic_string(lex["Segments"], _output='cv')
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/lingpy/sequence/sound_classes.py", line 881, in prosodic_string
    [int(t) for t in tokens2class(string, rcParams['art'],
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/lingpy/sequence/sound_classes.py", line 792, in tokens2class
    raise ValueError("[!] your sequence contains only unknown characters")
ValueError: [!] your sequence contains only unknown characters
